name: rise_and_shine
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^5.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Sora
      fonts:
        - asset: fonts/static/Sora-Thin.ttf
          weight: 100
        - asset: fonts/static/Sora-ExtraLight.ttf
          weight: 200
        - asset: fonts/static/Sora-Light.ttf
          weight: 300
        - asset: fonts/static/Sora-Regular.ttf
          weight: 400
        - asset: fonts/static/Sora-Medium.ttf
          weight: 500
        - asset: fonts/static/Sora-SemiBold.ttf
          weight: 600
        - asset: fonts/static/Sora-Bold.ttf
          weight: 700
        - asset: fonts/static/Sora-ExtraBold.ttf
          weight: 800
